// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: bubble.proto
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_bubble_2eproto__INCLUDED
#define GRPC_bubble_2eproto__INCLUDED

#include "bubble.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace bubble_grpc {

class SortingService final {
 public:
  static constexpr char const* service_full_name() {
    return "bubble_grpc.SortingService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Sort(::grpc::ClientContext* context, const ::bubble_grpc::SortRequest& request, ::bubble_grpc::SortResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bubble_grpc::SortResponse>> AsyncSort(::grpc::ClientContext* context, const ::bubble_grpc::SortRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bubble_grpc::SortResponse>>(AsyncSortRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bubble_grpc::SortResponse>> PrepareAsyncSort(::grpc::ClientContext* context, const ::bubble_grpc::SortRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bubble_grpc::SortResponse>>(PrepareAsyncSortRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Sort(::grpc::ClientContext* context, const ::bubble_grpc::SortRequest* request, ::bubble_grpc::SortResponse* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bubble_grpc::SortResponse>* AsyncSortRaw(::grpc::ClientContext* context, const ::bubble_grpc::SortRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bubble_grpc::SortResponse>* PrepareAsyncSortRaw(::grpc::ClientContext* context, const ::bubble_grpc::SortRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Sort(::grpc::ClientContext* context, const ::bubble_grpc::SortRequest& request, ::bubble_grpc::SortResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bubble_grpc::SortResponse>> AsyncSort(::grpc::ClientContext* context, const ::bubble_grpc::SortRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bubble_grpc::SortResponse>>(AsyncSortRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bubble_grpc::SortResponse>> PrepareAsyncSort(::grpc::ClientContext* context, const ::bubble_grpc::SortRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bubble_grpc::SortResponse>>(PrepareAsyncSortRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Sort(::grpc::ClientContext* context, const ::bubble_grpc::SortRequest* request, ::bubble_grpc::SortResponse* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::bubble_grpc::SortResponse>* AsyncSortRaw(::grpc::ClientContext* context, const ::bubble_grpc::SortRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bubble_grpc::SortResponse>* PrepareAsyncSortRaw(::grpc::ClientContext* context, const ::bubble_grpc::SortRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Sort_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Sort(::grpc::ServerContext* context, const ::bubble_grpc::SortRequest* request, ::bubble_grpc::SortResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Sort : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Sort() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Sort() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sort(::grpc::ServerContext* context, const ::bubble_grpc::SortRequest* request, ::bubble_grpc::SortResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSort(::grpc::ServerContext* context, ::bubble_grpc::SortRequest* request, ::grpc::ServerAsyncResponseWriter< ::bubble_grpc::SortResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Sort<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Sort : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Sort() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Sort() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sort(::grpc::ServerContext* context, const ::bubble_grpc::SortRequest* request, ::bubble_grpc::SortResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Sort : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_Sort() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Sort() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sort(::grpc::ServerContext* context, const ::bubble_grpc::SortRequest* request, ::bubble_grpc::SortResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSort(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Sort : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Sort() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::bubble_grpc::SortRequest, ::bubble_grpc::SortResponse>(std::bind(&WithStreamedUnaryMethod_Sort<BaseClass>::StreamedSort, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Sort() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Sort(::grpc::ServerContext* context, const ::bubble_grpc::SortRequest* request, ::bubble_grpc::SortResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSort(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::bubble_grpc::SortRequest,::bubble_grpc::SortResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Sort<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Sort<Service > StreamedService;
};

}  // namespace bubble_grpc


#endif  // GRPC_bubble_2eproto__INCLUDED
