// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bubble.proto

#include "bubble.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace bubble_grpc {
class SortRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SortRequest>
      _instance;
} _SortRequest_default_instance_;
class SortResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SortResponse>
      _instance;
} _SortResponse_default_instance_;
}  // namespace bubble_grpc
namespace protobuf_bubble_2eproto {
static void InitDefaultsSortRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bubble_grpc::_SortRequest_default_instance_;
    new (ptr) ::bubble_grpc::SortRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bubble_grpc::SortRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SortRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSortRequest}, {}};

static void InitDefaultsSortResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bubble_grpc::_SortResponse_default_instance_;
    new (ptr) ::bubble_grpc::SortResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bubble_grpc::SortResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SortResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSortResponse}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_SortRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SortResponse.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bubble_grpc::SortRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bubble_grpc::SortRequest, numbers_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bubble_grpc::SortResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bubble_grpc::SortResponse, numbers_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::bubble_grpc::SortRequest)},
  { 6, -1, sizeof(::bubble_grpc::SortResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::bubble_grpc::_SortRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::bubble_grpc::_SortResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "bubble.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014bubble.proto\022\013bubble_grpc\"\036\n\013SortReque"
      "st\022\017\n\007numbers\030\001 \003(\005\"\037\n\014SortResponse\022\017\n\007n"
      "umbers\030\001 \003(\0052O\n\016SortingService\022=\n\004Sort\022\030"
      ".bubble_grpc.SortRequest\032\031.bubble_grpc.S"
      "ortResponse\"\000b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 181);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "bubble.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_bubble_2eproto
namespace bubble_grpc {

// ===================================================================

void SortRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SortRequest::kNumbersFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SortRequest::SortRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_bubble_2eproto::scc_info_SortRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:bubble_grpc.SortRequest)
}
SortRequest::SortRequest(const SortRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      numbers_(from.numbers_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:bubble_grpc.SortRequest)
}

void SortRequest::SharedCtor() {
}

SortRequest::~SortRequest() {
  // @@protoc_insertion_point(destructor:bubble_grpc.SortRequest)
  SharedDtor();
}

void SortRequest::SharedDtor() {
}

void SortRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SortRequest::descriptor() {
  ::protobuf_bubble_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_bubble_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SortRequest& SortRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_bubble_2eproto::scc_info_SortRequest.base);
  return *internal_default_instance();
}


void SortRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:bubble_grpc.SortRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  numbers_.Clear();
  _internal_metadata_.Clear();
}

bool SortRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:bubble_grpc.SortRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 numbers = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_numbers())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 10u, input, this->mutable_numbers())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:bubble_grpc.SortRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:bubble_grpc.SortRequest)
  return false;
#undef DO_
}

void SortRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:bubble_grpc.SortRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 numbers = 1;
  if (this->numbers_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _numbers_cached_byte_size_));
  }
  for (int i = 0, n = this->numbers_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->numbers(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:bubble_grpc.SortRequest)
}

::google::protobuf::uint8* SortRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:bubble_grpc.SortRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 numbers = 1;
  if (this->numbers_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _numbers_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->numbers_, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bubble_grpc.SortRequest)
  return target;
}

size_t SortRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bubble_grpc.SortRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated int32 numbers = 1;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->numbers_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _numbers_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SortRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bubble_grpc.SortRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const SortRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SortRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bubble_grpc.SortRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bubble_grpc.SortRequest)
    MergeFrom(*source);
  }
}

void SortRequest::MergeFrom(const SortRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bubble_grpc.SortRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  numbers_.MergeFrom(from.numbers_);
}

void SortRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bubble_grpc.SortRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SortRequest::CopyFrom(const SortRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bubble_grpc.SortRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SortRequest::IsInitialized() const {
  return true;
}

void SortRequest::Swap(SortRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SortRequest::InternalSwap(SortRequest* other) {
  using std::swap;
  numbers_.InternalSwap(&other->numbers_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SortRequest::GetMetadata() const {
  protobuf_bubble_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_bubble_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SortResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SortResponse::kNumbersFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SortResponse::SortResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_bubble_2eproto::scc_info_SortResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:bubble_grpc.SortResponse)
}
SortResponse::SortResponse(const SortResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      numbers_(from.numbers_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:bubble_grpc.SortResponse)
}

void SortResponse::SharedCtor() {
}

SortResponse::~SortResponse() {
  // @@protoc_insertion_point(destructor:bubble_grpc.SortResponse)
  SharedDtor();
}

void SortResponse::SharedDtor() {
}

void SortResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SortResponse::descriptor() {
  ::protobuf_bubble_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_bubble_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SortResponse& SortResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_bubble_2eproto::scc_info_SortResponse.base);
  return *internal_default_instance();
}


void SortResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:bubble_grpc.SortResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  numbers_.Clear();
  _internal_metadata_.Clear();
}

bool SortResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:bubble_grpc.SortResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 numbers = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_numbers())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 10u, input, this->mutable_numbers())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:bubble_grpc.SortResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:bubble_grpc.SortResponse)
  return false;
#undef DO_
}

void SortResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:bubble_grpc.SortResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 numbers = 1;
  if (this->numbers_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _numbers_cached_byte_size_));
  }
  for (int i = 0, n = this->numbers_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->numbers(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:bubble_grpc.SortResponse)
}

::google::protobuf::uint8* SortResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:bubble_grpc.SortResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 numbers = 1;
  if (this->numbers_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _numbers_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->numbers_, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bubble_grpc.SortResponse)
  return target;
}

size_t SortResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bubble_grpc.SortResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated int32 numbers = 1;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->numbers_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _numbers_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SortResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bubble_grpc.SortResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const SortResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SortResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bubble_grpc.SortResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bubble_grpc.SortResponse)
    MergeFrom(*source);
  }
}

void SortResponse::MergeFrom(const SortResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bubble_grpc.SortResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  numbers_.MergeFrom(from.numbers_);
}

void SortResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bubble_grpc.SortResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SortResponse::CopyFrom(const SortResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bubble_grpc.SortResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SortResponse::IsInitialized() const {
  return true;
}

void SortResponse::Swap(SortResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SortResponse::InternalSwap(SortResponse* other) {
  using std::swap;
  numbers_.InternalSwap(&other->numbers_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SortResponse::GetMetadata() const {
  protobuf_bubble_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_bubble_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace bubble_grpc
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::bubble_grpc::SortRequest* Arena::CreateMaybeMessage< ::bubble_grpc::SortRequest >(Arena* arena) {
  return Arena::CreateInternal< ::bubble_grpc::SortRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::bubble_grpc::SortResponse* Arena::CreateMaybeMessage< ::bubble_grpc::SortResponse >(Arena* arena) {
  return Arena::CreateInternal< ::bubble_grpc::SortResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
