// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bubble.proto

#ifndef PROTOBUF_INCLUDED_bubble_2eproto
#define PROTOBUF_INCLUDED_bubble_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_bubble_2eproto 

namespace protobuf_bubble_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_bubble_2eproto
namespace bubble_grpc {
class SortRequest;
class SortRequestDefaultTypeInternal;
extern SortRequestDefaultTypeInternal _SortRequest_default_instance_;
class SortResponse;
class SortResponseDefaultTypeInternal;
extern SortResponseDefaultTypeInternal _SortResponse_default_instance_;
}  // namespace bubble_grpc
namespace google {
namespace protobuf {
template<> ::bubble_grpc::SortRequest* Arena::CreateMaybeMessage<::bubble_grpc::SortRequest>(Arena*);
template<> ::bubble_grpc::SortResponse* Arena::CreateMaybeMessage<::bubble_grpc::SortResponse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace bubble_grpc {

// ===================================================================

class SortRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:bubble_grpc.SortRequest) */ {
 public:
  SortRequest();
  virtual ~SortRequest();

  SortRequest(const SortRequest& from);

  inline SortRequest& operator=(const SortRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SortRequest(SortRequest&& from) noexcept
    : SortRequest() {
    *this = ::std::move(from);
  }

  inline SortRequest& operator=(SortRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SortRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SortRequest* internal_default_instance() {
    return reinterpret_cast<const SortRequest*>(
               &_SortRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(SortRequest* other);
  friend void swap(SortRequest& a, SortRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SortRequest* New() const final {
    return CreateMaybeMessage<SortRequest>(NULL);
  }

  SortRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SortRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SortRequest& from);
  void MergeFrom(const SortRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SortRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 numbers = 1;
  int numbers_size() const;
  void clear_numbers();
  static const int kNumbersFieldNumber = 1;
  ::google::protobuf::int32 numbers(int index) const;
  void set_numbers(int index, ::google::protobuf::int32 value);
  void add_numbers(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      numbers() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_numbers();

  // @@protoc_insertion_point(class_scope:bubble_grpc.SortRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > numbers_;
  mutable int _numbers_cached_byte_size_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_bubble_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SortResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:bubble_grpc.SortResponse) */ {
 public:
  SortResponse();
  virtual ~SortResponse();

  SortResponse(const SortResponse& from);

  inline SortResponse& operator=(const SortResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SortResponse(SortResponse&& from) noexcept
    : SortResponse() {
    *this = ::std::move(from);
  }

  inline SortResponse& operator=(SortResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SortResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SortResponse* internal_default_instance() {
    return reinterpret_cast<const SortResponse*>(
               &_SortResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(SortResponse* other);
  friend void swap(SortResponse& a, SortResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SortResponse* New() const final {
    return CreateMaybeMessage<SortResponse>(NULL);
  }

  SortResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SortResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SortResponse& from);
  void MergeFrom(const SortResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SortResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 numbers = 1;
  int numbers_size() const;
  void clear_numbers();
  static const int kNumbersFieldNumber = 1;
  ::google::protobuf::int32 numbers(int index) const;
  void set_numbers(int index, ::google::protobuf::int32 value);
  void add_numbers(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      numbers() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_numbers();

  // @@protoc_insertion_point(class_scope:bubble_grpc.SortResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > numbers_;
  mutable int _numbers_cached_byte_size_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_bubble_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SortRequest

// repeated int32 numbers = 1;
inline int SortRequest::numbers_size() const {
  return numbers_.size();
}
inline void SortRequest::clear_numbers() {
  numbers_.Clear();
}
inline ::google::protobuf::int32 SortRequest::numbers(int index) const {
  // @@protoc_insertion_point(field_get:bubble_grpc.SortRequest.numbers)
  return numbers_.Get(index);
}
inline void SortRequest::set_numbers(int index, ::google::protobuf::int32 value) {
  numbers_.Set(index, value);
  // @@protoc_insertion_point(field_set:bubble_grpc.SortRequest.numbers)
}
inline void SortRequest::add_numbers(::google::protobuf::int32 value) {
  numbers_.Add(value);
  // @@protoc_insertion_point(field_add:bubble_grpc.SortRequest.numbers)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
SortRequest::numbers() const {
  // @@protoc_insertion_point(field_list:bubble_grpc.SortRequest.numbers)
  return numbers_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
SortRequest::mutable_numbers() {
  // @@protoc_insertion_point(field_mutable_list:bubble_grpc.SortRequest.numbers)
  return &numbers_;
}

// -------------------------------------------------------------------

// SortResponse

// repeated int32 numbers = 1;
inline int SortResponse::numbers_size() const {
  return numbers_.size();
}
inline void SortResponse::clear_numbers() {
  numbers_.Clear();
}
inline ::google::protobuf::int32 SortResponse::numbers(int index) const {
  // @@protoc_insertion_point(field_get:bubble_grpc.SortResponse.numbers)
  return numbers_.Get(index);
}
inline void SortResponse::set_numbers(int index, ::google::protobuf::int32 value) {
  numbers_.Set(index, value);
  // @@protoc_insertion_point(field_set:bubble_grpc.SortResponse.numbers)
}
inline void SortResponse::add_numbers(::google::protobuf::int32 value) {
  numbers_.Add(value);
  // @@protoc_insertion_point(field_add:bubble_grpc.SortResponse.numbers)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
SortResponse::numbers() const {
  // @@protoc_insertion_point(field_list:bubble_grpc.SortResponse.numbers)
  return numbers_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
SortResponse::mutable_numbers() {
  // @@protoc_insertion_point(field_mutable_list:bubble_grpc.SortResponse.numbers)
  return &numbers_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace bubble_grpc

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_bubble_2eproto
