# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mateusz/Repos/bubble-grpc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mateusz/Repos/bubble-grpc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mateusz/Repos/bubble-grpc/CMakeFiles /home/mateusz/Repos/bubble-grpc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mateusz/Repos/bubble-grpc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sort_server

# Build rule for target.
sort_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sort_server
.PHONY : sort_server

# fast build rule for target.
sort_server/fast:
	$(MAKE) -f CMakeFiles/sort_server.dir/build.make CMakeFiles/sort_server.dir/build
.PHONY : sort_server/fast

#=============================================================================
# Target rules for targets named sort_client

# Build rule for target.
sort_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sort_client
.PHONY : sort_client

# fast build rule for target.
sort_client/fast:
	$(MAKE) -f CMakeFiles/sort_client.dir/build.make CMakeFiles/sort_client.dir/build
.PHONY : sort_client/fast

#=============================================================================
# Target rules for targets named b_grpc_proto

# Build rule for target.
b_grpc_proto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 b_grpc_proto
.PHONY : b_grpc_proto

# fast build rule for target.
b_grpc_proto/fast:
	$(MAKE) -f CMakeFiles/b_grpc_proto.dir/build.make CMakeFiles/b_grpc_proto.dir/build
.PHONY : b_grpc_proto/fast

bubble.grpc.pb.o: bubble.grpc.pb.cc.o

.PHONY : bubble.grpc.pb.o

# target to build an object file
bubble.grpc.pb.cc.o:
	$(MAKE) -f CMakeFiles/b_grpc_proto.dir/build.make CMakeFiles/b_grpc_proto.dir/bubble.grpc.pb.cc.o
.PHONY : bubble.grpc.pb.cc.o

bubble.grpc.pb.i: bubble.grpc.pb.cc.i

.PHONY : bubble.grpc.pb.i

# target to preprocess a source file
bubble.grpc.pb.cc.i:
	$(MAKE) -f CMakeFiles/b_grpc_proto.dir/build.make CMakeFiles/b_grpc_proto.dir/bubble.grpc.pb.cc.i
.PHONY : bubble.grpc.pb.cc.i

bubble.grpc.pb.s: bubble.grpc.pb.cc.s

.PHONY : bubble.grpc.pb.s

# target to generate assembly for a file
bubble.grpc.pb.cc.s:
	$(MAKE) -f CMakeFiles/b_grpc_proto.dir/build.make CMakeFiles/b_grpc_proto.dir/bubble.grpc.pb.cc.s
.PHONY : bubble.grpc.pb.cc.s

bubble.pb.o: bubble.pb.cc.o

.PHONY : bubble.pb.o

# target to build an object file
bubble.pb.cc.o:
	$(MAKE) -f CMakeFiles/b_grpc_proto.dir/build.make CMakeFiles/b_grpc_proto.dir/bubble.pb.cc.o
.PHONY : bubble.pb.cc.o

bubble.pb.i: bubble.pb.cc.i

.PHONY : bubble.pb.i

# target to preprocess a source file
bubble.pb.cc.i:
	$(MAKE) -f CMakeFiles/b_grpc_proto.dir/build.make CMakeFiles/b_grpc_proto.dir/bubble.pb.cc.i
.PHONY : bubble.pb.cc.i

bubble.pb.s: bubble.pb.cc.s

.PHONY : bubble.pb.s

# target to generate assembly for a file
bubble.pb.cc.s:
	$(MAKE) -f CMakeFiles/b_grpc_proto.dir/build.make CMakeFiles/b_grpc_proto.dir/bubble.pb.cc.s
.PHONY : bubble.pb.cc.s

sort_client.o: sort_client.cc.o

.PHONY : sort_client.o

# target to build an object file
sort_client.cc.o:
	$(MAKE) -f CMakeFiles/sort_client.dir/build.make CMakeFiles/sort_client.dir/sort_client.cc.o
.PHONY : sort_client.cc.o

sort_client.i: sort_client.cc.i

.PHONY : sort_client.i

# target to preprocess a source file
sort_client.cc.i:
	$(MAKE) -f CMakeFiles/sort_client.dir/build.make CMakeFiles/sort_client.dir/sort_client.cc.i
.PHONY : sort_client.cc.i

sort_client.s: sort_client.cc.s

.PHONY : sort_client.s

# target to generate assembly for a file
sort_client.cc.s:
	$(MAKE) -f CMakeFiles/sort_client.dir/build.make CMakeFiles/sort_client.dir/sort_client.cc.s
.PHONY : sort_client.cc.s

sort_server.o: sort_server.cc.o

.PHONY : sort_server.o

# target to build an object file
sort_server.cc.o:
	$(MAKE) -f CMakeFiles/sort_server.dir/build.make CMakeFiles/sort_server.dir/sort_server.cc.o
.PHONY : sort_server.cc.o

sort_server.i: sort_server.cc.i

.PHONY : sort_server.i

# target to preprocess a source file
sort_server.cc.i:
	$(MAKE) -f CMakeFiles/sort_server.dir/build.make CMakeFiles/sort_server.dir/sort_server.cc.i
.PHONY : sort_server.cc.i

sort_server.s: sort_server.cc.s

.PHONY : sort_server.s

# target to generate assembly for a file
sort_server.cc.s:
	$(MAKE) -f CMakeFiles/sort_server.dir/build.make CMakeFiles/sort_server.dir/sort_server.cc.s
.PHONY : sort_server.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... sort_server"
	@echo "... rebuild_cache"
	@echo "... sort_client"
	@echo "... b_grpc_proto"
	@echo "... bubble.grpc.pb.o"
	@echo "... bubble.grpc.pb.i"
	@echo "... bubble.grpc.pb.s"
	@echo "... bubble.pb.o"
	@echo "... bubble.pb.i"
	@echo "... bubble.pb.s"
	@echo "... sort_client.o"
	@echo "... sort_client.i"
	@echo "... sort_client.s"
	@echo "... sort_server.o"
	@echo "... sort_server.i"
	@echo "... sort_server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

